### ISSUE TITLE
Park names are not visible with imagery

### ISSUE THREAD

**Issue by vwolfley** [AZMAG/map-RecreationViewer#55]

**Comment by nfunicello** [comment]
I think the issue is the detailed park points which are black dots with black labels can't be seen against the dark imagery. Can we try to give them a halo or can the color of the labels change if a imagery is selected as a basemap?

**Comment by Jfairfield1** [comment]
Got this fixed.  I switched the color of the labels when the imagery is selected and the user is zoomed in to the detailed extent.
